### ISSUE TITLE
Unable to sync due to sign in failure

### ISSUE THREAD

**Issue by thewithz** [JASchilz/AnkiSyncDuolingo#33]
My account doesn't use Facebook or Google credentials. 
I am able to sign out and log back into the Duolingo website successfully, however, my credentials no longer work when input into the plugin on Anki.

**Comment by MartiiDev** [comment]
+1, I have the exact same problem

**Comment by SakiHaryayin** [comment]
I have the same problem. Using Anki 2.1.40 on MacBook OS 10.13.

**Comment by JASchilz** [comment]
Thank you all for raising this! It looks like this is due to a change in the Duolingo servers.  The code library that I'm using to communicate with Duolingo [also noted this problem](https://github.com/KartikTalwar/Duolingo/issues/102) and has a fix. I'll have a fix published in a couple of hours.

**Comment by JASchilz** [comment]
Hi folks! This should be resolved with the latest release of the plugin.

You should be able to upgrade your copy of the plugin in Anki with:
  * "Tools" -> "Add-ons"
  * Select "Pull from Duolingo"
  * Click "Check for Updates"

I'm going to leave this issue open for a while longer, so that users following the support link from Anki will be able to find it.

**Comment by SakiHaryayin** [comment]
I am able to log in now. Thank so much for the quick fix!!
