### ISSUE TITLE
Improvement Suggestion - Text to Audio

### ISSUE THREAD

**Issue by fredrikcoulter** [JASchilz/AnkiSyncDuolingo#41]
I'm a very happy user of your Addon.  I've been pulling in my French words, and it's helping me keep my words in memory.

However, there is one thing that I'd really like to see added to your addon.  You've been pulling in the pronunciation information from Duolingo, but it doesn't go anywhere.  It's not in your new card definitions.

Now, I've seen other addons that turn cards into spoken text.  It would be really nice if you could combine all that and have the foreign language side of the card also say the card out loud.  That would be a very nice improvement to the addon, although not at all necessary.

(I suppose instructions for adding that capability using other addons would also be useful.)

**Comment by JASchilz** [comment]
I can see where this would be useful!

I've taken a quick look through the "Awesome TTS" plugin. At a glance, it looks like you might be able to add speech to a card without even using the pronunciation text from Duolingo: it looks like you can just add it to the "written" version of the foreign text, and that particular plugin will produce a pronunciation based on that written version. The instructions are a bit advanced, but I think it might already be possible to apply them to the existing cards.

That said, you can also definitely add the pronunciation text from Duolingo. I pull it down from Duolingo so that individuals can put it into the cards if they want to, but by default I don't include it as some people wouldn't want it. I'll explain how to do that, if you're interested, but one piece of Anki terminology will help if you don't already know it:
  * The plugin converts every foreign/native language word pair into a "note". The "note" captures the foreign version of the word, your native version, plus gender and pronunciation if applicable. So, for example, you have a "note" for the word "oui" that includes the English translation "yes".
  * There are different "types" of notes that can capture different bits of information. This plugin creates a "Duolingo Sync" note type.
  * Every note type has associated "cards". By default, the "Duolingo Sync" note type has a card with the "oui" on the front and "yes" on the back, and also a card type with "yes" on the front and "oui" on the back.
  * But you can edit those cards to include more information, or even add extra information from the note, like the pronunciation.

OK! So if you want to add the pronunciation:
  * Open Anki
  * Click "Tools" -> "Manage Note Types" -> Single click "Duolingo Sync" -> Then click the "Cards" button.
  * Now you can modify the cards associated with the note type. For example, you could click on "Back Template" and where you see "{{Target}}" you could add "{{Pronunciation}}".

Bear in mind that if you were to modify one card type in a note type, you might (or might not) want to edit the others as well. And you can also make more than two card types, if you want! You might have to experiment a bit with styling: you can use some really basic styling from HTML (like "`<br>`" for line breaks), but that might be pretty foreign if you don't have experience with it.

A few people have asked about modifying the cards with that extra information, like pronunciation, so I'm going to leave this open until I can find a good tutorial that can help people make those kinds of edits.

Based on what I've seen in the text to speech plugins, it looks like I should probably leave that expertise to another plugin, but just make sure that there's a way for people to figure out how to use the two together.

**Comment by JASchilz** [comment]
From https://github.com/JASchilz/AnkiSyncDuolingo/issues/49, it looks like this might be a thing that's possible without direct integration into this plugin.
