### ISSUE TITLE
Failed login causes Anki to become locked/unusable

### ISSUE THREAD

**Issue by panssystem** [JASchilz/AnkiSyncDuolingo#45]
On Windows (10,11) when I typo the login, which happens more than I'd like, Anki ends up in an unusable state and I must kill it from the task manager.

What I think is happening is that it pops up the "failed login" dialog, but the progress bar dialog still has focus (and is modal?), so I can't acknowledge the failed login, and the only way to interact with Anki is to kill it and restart.

**Comment by JASchilz** [comment]
Thanks for reporting this!

I'm on Windows and I'm not able to reproduce this myself:
  * When I mistype my password and get a failed login.
  * The "failed login" dialog pops up, and I'm able to acknowledge the
failure and not get locked up.

However, I DO confirm that the "failed login" dialog pops up while the
progress bar dialog is still open, and I can imagine how this would cause
problems for some configurations. So since it's causing a problem for you,
it's probably causing a problem for others as well and it seems like a good
thing to fix.

I don't touch this project often, so I might not address this in the next
few weeks, but it is currently the number one bug that I'd like to address
when I next touch this project.

**Comment by JASchilz** [comment]
Hi @panssystem ! I was never able to reproduce this, but I did recently overhaul how I was interacting with the Anki graphics system, and that might have solved a number of weird issues.

If you were to [update to the latest version from Ankiweb](https://ankiweb.net/shared/info/557761805) (and then restart Anki), I'd be curious to know if that solves your issue.

I'll close this in a week if I don't hear from you, but please do feel free to re-open the issue if this hasn't solved it!
