### ISSUE TITLE
Include illustrations from Duolingo

### ISSUE THREAD

**Issue by ebanDev** [JASchilz/AnkiSyncDuolingo#46]
Hey ! Could be cool to be able to import Duolingo's illustrations in card

**Comment by JASchilz** [comment]
That does definitely seem like a useful feature to have! Sadly, it's not a feature that Duolingo makes available to plugins like these.

I can say that when I'm doing my initial review of cards, I often like searching Google Images for art that I can use in place of the English translation, like a picture of a banana instead of the word "banana" etc.
