### ISSUE TITLE
How to set default deck

### ISSUE THREAD

**Issue by fredrikcoulter** [JASchilz/AnkiSyncDuolingo#48]
Pull from Duolingo adds cards to the default deck.  How can set a deck as the default deck?

Or do I need to rename the existing default deck and then move all the non-language cards and notes out of that deck?

Imported cards are NOT being placed in the deck with the name Default.

**Comment by jameskraus** [comment]
It may be possible to implement a very basic version of this via the built-in config editor:
![2023-03-13 00 34 39](https://user-images.githubusercontent.com/415057/224609185-d2a94274-c09d-495e-9246-d2251ad847d6.gif)

@JASchilz thoughts? Open to a PR along those lines?

**Comment by JASchilz** [comment]
Thanks @jameskraus et. al! I'm going to go ahead and close this issue to reflect:
  * James's work to make it so that cards actually go into the deck that's considered default by Anki, even if you've renamed it.
  * You can use the tags that this plugin creates to select and move cards from the default deck into another deck of choice.

I'll leave https://github.com/JASchilz/AnkiSyncDuolingo/issues/44 open to capture the feature request of being able to change which deck AnkiSyncDuolingo deposits its cards into.
