### ISSUE TITLE
download successful > no new vocabulary > cant find the items in default

### ISSUE THREAD

**Issue by arikd** [JASchilz/AnkiSyncDuolingo#52]
Hello,

using the plugin is no problem. it is checking the vocabulary (unfortunately not downloading because they are already there somewhere)

I cannot see these items.

can you help me to make them visible to be able to study them?
Thank you.

**Comment by MaxJuettner** [comment]
I have the same problem. Is there already a solution?

**Comment by JASchilz** [comment]
Hi Max!

Hmm....this _should_ show up under your Default deck. I tried reproducing
this by downloading the latest version of Anki and performing a fresh sync
on a new profile, and they did show up.

I do notice that the interface has undergone some changes since I last
touched this project, so I wouldn't be totally surprised if some change has
broken this. What version of Anki are you using?

Could you try confirming that the cards aren't in your default deck? You
could open up your default deck, then click "Browse" and then try searching
for cards with the tag:duolingo_sync

[image: image.png]
