### ISSUE TITLE
Support for new Anki versions (23.10)

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [JASchilz/AnkiSyncDuolingo#74]
Attempting to install this from the plugin list results in:

<img width="372" alt="image" src="https://github.com/JASchilz/AnkiSyncDuolingo/assets/200/673d9591-a89f-4d59-91e6-86973054364b">

**Comment by spcified** [comment]
You can add it by file, instead of code. I guess the dev has to specify the applicable versions on Anki's addon page as there is no version stated inside manifest.json

Just tried it and i was able to pull my words with Anki version 23.10.1

**Comment by JASchilz** [comment]
Hi @ELLIOTTCABLE ! I hope @spcified 's solution worked for you.

I no longer publish this add-on to AnkiWeb because occasional changes by Duolingo to their service cause this plugin to break. It's only available here on GitHub. And you can see the list of most recent releases at https://github.com/JASchilz/AnkiSyncDuolingo/releases.
